baseURL = "https://cbhds-dbengine.github.io/CBhDS-Site/"
languageCode = "fr-fr"
title = "CBhDS - Portfolio Technique pour SQL Server"
theme = "PaperMod"

# Configuration automatique du Sitemap pour Google
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  env = "production" # 2. Force PaperMod à activer l'optimisation SEO de production
  description = "SQL Server Production Engineering"
  defaultTheme = "dark"
  ShowCodeCopyButtons = true
  mainSections = ["docker-sqlserver-lab", "community","automation"]

[menu]

  [[menu.main]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/chbrault-dba/"
    weight = 1

  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "CV-CBrault.pdf"
    weight = 2
    
  [[menu.main]]
    identifier = "docker"
    name = "Docker Lab"
    url = "/docker-sqlserver-lab/"
    weight = 3

  [[menu.main]]
    identifier = "automation"
    name = "DevOps-Automation"
    url = "/categories/automation/"
    weight = 4

  [[menu.main]]
    identifier = "community"
    name = "Community resources"
    url = "/community/"
    weight = 5

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 6

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 7

[params.assets]
customCSS = ["css/custom.css"]
