baseURL = "https://cbhds-dbengine.github.io/CBhDS-Site/"
languageCode = "fr-fr"
title = "CBhDS - Portfolio Technique pour SQL Server"
theme = "PaperMod"

[params]
  description = "SQL Server Production Engineering"
  defaultTheme = "dark"
  ShowCodeCopyButtons = true
  mainSections = ["docker-sqlserver-lab", "community"]

[menu]

  [[menu.main]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/chbrault-dba/"
    weight = 1

  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/CV-CBrault.pdf"
    weight = 2

[params.assets]
customCSS = ["css/custom.css"]
