baseURL = "https://cbhds-dbengine.github.io/CBhDS-Site/"
languageCode = "fr-fr"
title = "CBhDS - Portfolio Technique pour SQL Server"
theme = "PaperMod"

[taxonomies]
category = "categories"
tag = "tags"

[params]
  description = "SQL Server Production Engineering"
  defaultTheme = "dark"
  ShowCodeCopyButtons = true
  mainSections = ["docker-sqlserver-lab", "community","automation"]

[menu]

  [[menu.main]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/chbrault-dba/"
    weight = 1

  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "CV-CBrault.pdf"
    weight = 2
    
  [[menu.main]]
    identifier = "categories"
    name = "Catégories"
    url = "/categories/"
    weight = 3

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 4

[params.assets]
customCSS = ["css/custom.css"]
